### ISSUE TITLE
Allow deletion of dictionary entries

### ISSUE THREAD

**Issue by svenha** [fquirin/kaldi-adapt-lm#1]
This tool allows to add new entries to the dictionary or modify the pronunciation of existant entries. Deletions are not possible, but an entry without pronunciation could be used to mean deletion. If this is ok, I can open a small PR for this.

**Comment by fquirin** [comment]
Hi @svenha 
Do you mean you want to use empty entries (word - <empty>) in the list to add new words just to delete words from the dictionary?
Can you describe a bit more why you need this? Because if the word is not used in your language model it doesn't really matter if its in the dictionary or not.
That said I would be willing to accept a PR to do this anyway ;-)

**Comment by svenha** [comment]
Yes, I could filter my `lm_corpus/sentences.txt` instead.  But a typical use case is that you discover that two words are often confused by kaldi and you know that you will never need one of them (because it's rare, a non-word or ...). If `sentences.txt` is huge, it is more convenient to add a deletion entry (just: word, without -) to the local dictionary.

See pull request #2

**Comment by fquirin** [comment]
I've commented your PR :-)

One thing I was wondering. If you keep the word in your language model, but remove it from the lexicon this will probably create an error message during LM generation :thinking: 
Did you test this case?

I was planning to do some vocab check before but haven't had the time yet.

**Comment by svenha** [comment]
> If you keep the word in your language model, but remove it from the lexicon this will probably create an error message during LM generation

No. The language model is rebuilt with `lmplz ... --limit_vocab_file vocab.txt` and `vocab.txt` is updated correctly; I checked this now for my experiments.

**Comment by fquirin** [comment]
Ok, ty. I've merged the PR :-)
